# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048m

# KSP
ksp.useKSP2=true

# Hilt
dagger.hilt.disableModulesHaveInstallCheck=false

# Required by some libraries (e.g., androidx.webkit on AGP 8.x)
android.suppressUnsupportedCompileSdk=35
